---
driver:
  name: vagrant
  provider: <%= ENV['KITCHEN_PROVIDER'] || 'virtualbox' %>

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 3
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

platforms:
  - name: ubuntu-18.04
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: centos-7.1
  - name: centos-6.7

suites:
  - name: default
    run_list:
    attributes:
  - name: full
    run_list:
    attributes:
    verifier:
        name: inspec
