---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: '(files|templates)/patch-*'
      - id: trailing-whitespace
        exclude: '(files|templates)/patch-*'
      - id: check-added-large-files
      - id: check-json
      - id: detect-private-key
      - id: check-case-conflict
      - id: double-quote-string-fixer
      - id: requirements-txt-fixer
      - id: check-ast
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      # - id: detect-aws-credentials
      - id: check-docstring-first
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        args: [-I, .codespellignore]
  - repo: https://github.com/aristanetworks/j2lint.git
    rev: v1.1.0
    hooks:
      - id: j2lint
  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.9.2
    hooks:
      - id: ansible-lint
        files: \.(yaml|yml)$
#  - repo: git@github.com:Yelp/detect-secrets
#    rev: v1.1.0
#    hooks:
#      - id: detect-secrets
#        args: ['--baseline', '.secrets.baseline']
#        exclude: .*/tests/.*
