---
## https://isc.sans.edu/forums/diary/Improving+Bash+Forensics+Capabilities/20887/
## https://blog.rootshell.be/2009/02/28/bash-history-to-syslog/
## Syslog option is a compile option in bash, mostly not enabled
## https://bugzilla.redhat.com/show_bug.cgi?id=1323808
## https://lists.gnu.org/archive/html/bug-bash/2017-01/msg00053.html
## https://tiswww.case.edu/php/chet/bash/NEWS   5.0
##      aa. There is a new (disabled by default, undocumented) shell option to enable
##          and disable sending history to syslog at runtime.
## https://www.scip.ch/en/?labs.20150604 = auditd, rootsh, pam_tty_audit.so, sudo
## FIXME! activity from screen not logged (tmux OK), neither after sudo -s
## https://debian-administration.org/article/88/Monitoring_user_activity_via_snoopy https://github.com/a2o/snoopy

## https://administratosphere.wordpress.com/2011/05/20/logging-every-shell-command/
## https://stackoverflow.com/questions/15753234/scoping-anomalies-with-typeset-r-and-readonly-keywords-in-ksh
- name: Enforce tighter bash settings
  ansible.builtin.blockinfile:
    dest: /etc/profile
    marker: "### {mark} ANSIBLE MANAGED BLOCK: bash settings ###"
    content: |
      export HISTCONTROL=
      export HISTFILE=$HOME/.bash_history
      export HISTFILESIZE={{ harden_bash_histfilesize | default(5000) }}
      export HISTIGNORE=
      export HISTSIZE={{ harden_bash_histsize | default(5000) }}
      export HISTTIMEFORMAT="{{ harden_bash_histtimeformat | default('%a %b %Y %T %z') }}"
      if [ "`id -u`" -eq 0 ]; then
        export PS1="{{ harden_bash_ps1_root | default('[\A] \u@\h {\W}\\# ') }}"
      else
        export PS1="{{ harden_bash_ps1 | default('[\A] \u@\h {\W}\\$ ') }}"
      fi
      if [ "X$SHELL" = '/bin/bash' ]; then
      typeset -r HISTCONTROL
      typeset -r HISTFILE
      typeset -r HISTFILESIZE
      typeset -r HISTIGNORE
      typeset -r HISTSIZE
      typeset -r HISTTIMEFORMAT
      fi
  tags: bash
## those two seems to create issues...
#      export PROMPT_COMMAND=\"history -a\"
#      typeset -r PROMPT_COMMAND

## Note: does not apply to ansible (direct call to python?) or root bash (why?)
## empty command are? typeset?
- name: Enable syslog logging of shell command through /etc/profile
  ansible.builtin.blockinfile:
    dest: /etc/profile
    marker: "### {mark} ANSIBLE MANAGED BLOCK: bash2syslog ###"
    content: |
      if [ "X$SHELL" = '/bin/bash' ]; then
      function log2syslog
      {
         declare command
         command=$(fc -ln -0)
         [ "X$command" != "X" ] && logger -p local1.notice -t bash -i -- $USER[PWD: $PWD] from $SSH_CLIENT: $command
      }
      trap log2syslog DEBUG
      fi
  tags: bash
