---

- name: Configure chkrootkit
  ansible.builtin.copy:
    src: "{{ harden_chkrootkit_conf }}"
    dest: /etc/chkrootkit/chkrootkit.conf
    mode: '0644'
    backup: yes

- name: Add ignore to chkrootkit
  ansible.builtin.lineinfile:
    path: /etc/chkrootkit/chkrootkit.ignore
    line: "{{ item }}"
    mode: '0644'
  loop: "{{ harden_chkrootkit_ignore }}"

- name: Check if log.expected exists
  ansible.builtin.stat:
    path: /var/log/chkrootkit/log.expected
  register: chkr_expected
- name: Check if log.today exists
  ansible.builtin.stat:
    path: /var/log/chkrootkit/log.today
  register: chkr_today
- name: Set log.expected
  ansible.builtin.copy:
    src: /var/log/chkrootkit/log.today
    dest: /var/log/chkrootkit/log.expected
    mode: '0644'
    owner: root
    remote_src: true
  when:
    - not chkr_expected.stat.exists
    - chkr_today.stat.exists
