---
# https://askubuntu.com/questions/1025309/how-can-i-disable-llmnr-in-systemd-resolved
# https://www.freedesktop.org/software/systemd/man/systemd-resolved.service.html
# https://www.blackhillsinfosec.com/how-to-disable-llmnr-why-you-want-to/

- name: Check if systemd-resolved is present
  ansible.builtin.stat:
    path: /etc/systemd/resolved.conf
  register: sysres

- name: Systemd-resolved
  when: sysres.stat.exists
  block:
    - name: Ensure LLMNR is disabled in systemd-resolved
      ansible.builtin.lineinfile:
        dest: /etc/systemd/resolved.conf
        regexp: '^LLMNR=.*'
        line: 'LLMNR=no'
        mode: '0644'
        backup: "{{ harden_backup | default(false) }}"
      notify:
        - Restart systemd-resolved
