---
## https://access.redhat.com/articles/2475321
## RHEL7.2+

- name: Ensure kpatch is present
  ansible.builtin.dnf:
    name: kpatch
    state: present
  register: pkg_result
  until: pkg_result is success

- name: Check kpatch applied
  ansible.builtin.command: kpatch --list
  changed_when: false
  failed_when: false
