---
## https://access.redhat.com/articles/2475321
## RHEL7.2+

- name: Ensure kpatch is present
  yum:
    name: kpatch
    state: present
  register: pkg_result
  until: pkg_result is success

- name: check kpatch applied
  command: kpatch --list
  changed_when: false
  failed_when: false
