---

- name: Debug | harden_rootforward var
  ansible.builtin.debug:
    var: harden_rootforward
- name: Forward all root email
  ansible.builtin.lineinfile:
    dest: /root/.forward
    line: "{{ harden_rootforward }}"
    mode: '0600'
    state: present
    create: True
