---

- name: Debug | harden_rootforward var
  debug: var=harden_rootforward
- name: Forward all root email
  lineinfile:
    dest: /root/.forward
    line: "{{ harden_rootforward }}"
    mode: '0600'
    state: present
    create: True
