---

- name: Clean /etc/securetty configuration
  ansible.builtin.lineinfile:
    dest: /etc/securetty
    regexp: "{{ item }}"
    state: absent
    backup: "{{ harden_backup | default(false) }}"
  with_items:
    - '^hvc*'
    - '^hvs*'
    - '^xvc*'
    - '^ttyS*'
    - '^ttysclp*'
    - '^sclp_line*'
    - '^3270/tty*'
