---

- name: Configure ssh client options system-wide
  ansible.builtin.template:
    src: "{{ harden_ssh_template }}"
    dest: /etc/ssh/ssh_config
    mode: '0644'
    backup: "{{ harden_backup | default(false) }}"
