---

- name: Testing | Ensure testing packages are present
  package:
     name: "{{ testing_pkgs }}"
     state: present

- block:
#    - name: testing | Ensure ruby and dependencies are present
#      package:
#        name: "{{ item }}"
#        state: present
#      with_items: "{{ testing_pkgs }}"
#    - name: testing | Ensure inspec is present
#      gem:
#        name: "{{ item }}"
#        state: present
#        user_install: no
#      with_items:
#        - rake
#        - inspec
    - name: download inspec package
      get_url:
        url: "{{ inspec_url }}"
        dest: "/tmp/{{ inspec_url | basename }}"
        checksum: "{{ inspec_hash }}"
        mode: '0600'
      register: dl_result
      until: dl_result is success
    - name: Debian | install chef public key for inspec package
      apt_key:
        url: https://packages.chef.io/chef.asc
        state: present
      when: ansible_os_family == 'Debian'
      register: pkg_result
      until: pkg_result is success
    - name: Debian | install inspec package
      apt:
        deb: "/tmp/{{ inspec_url | basename }}"
        state: present
      when: ansible_os_family == 'Debian'
      register: pkg_result
      until: pkg_result is success
    - name: RedHat | install chef public key for inspec package
      rpm_key:
        key: https://packages.chef.io/chef.asc
        state: present
      when: ansible_os_family == 'RedHat'
      register: pkg_result
      until: pkg_result is success
    - name: RedHat | install inspec package
      yum:
        name: "/tmp/{{ inspec_url | basename }}"
        state: present
      when: ansible_os_family == 'RedHat'
      register: pkg_result
      until: pkg_result is success

    - name: testing | accept inspec license - directory
      file:
        path: /etc/chef/accepted_licenses
        state: directory
        mode: '0755'

    # https://github.com/chef/automate/issues/83
    # https://github.com/chef/automate/pull/95 (alternative with ENV)
    - name: testing | accept inspec license
      file:
        path: /etc/chef/accepted_licenses/inspec
        state: touch

    - name: testing | run linux-baseline
#      shell: "inspec exec {{ harden_testing_inspec_paths | join(' ') }} | tee /var/log/inspec.log"
      shell: >
        inspec exec inspec --attrs inspec/profile-attributes-{{ ansible_os_family }}.yml |
            tee {{ log_dir | default('/var/log') }}/inspec.log |
            sed -r "s/\\x1B\\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"
      args:
        chdir: "{{ inspec_dir | default('/tmp/kitchen/juju4.harden/test/integration/default') }}"
        creates: "{{ log_dir | default('/var/log') }}/inspec.log"
      ignore_errors: true
      register: inspeclog
      changed_when: false
    - debug: var=inspeclog.stdout_lines

    - name: testing | run inspec baselines
      shell: >
        inspec exec {{ item.u }} --attrs inspec/profile-attributes-{{ ansible_os_family }}.yml |
            tee -a {{ log_dir | default('/var/log') }}/inspec-{{ item.i }}.log |
            sed -r "s/\\x1B\\[([0-9]{1,2}(;[0-9]{1,2})?)?[mGK]//g"
      args:
        chdir: "{{ inspec_dir | default('/tmp/kitchen/juju4.harden/test/integration/default') }}"
        creates: "/var/log/inspec-{{ item.i }}.log"
      with_items: "{{ harden_testing_inspec_paths }}"
      ignore_errors: true
      changed_when: false

  when: harden_testing_inspec and (ansible_os_family == "Debian" or ansible_os_family == "RedHat")

- include: testing-check.yml
  when: harden_testing_check

- include: testing-privesc.yml
  when: harden_testing_privesc

- include: testing-speculative.yml
  when: harden_testing_speculative
