---

- name: Testing | Ensure testing packages are present
  ansible.builtin.package:
    name: "{{ testing_pkgs }}"
    state: present

- name: Import testing-check
  ansible.builtin.import_tasks: testing-check.yml
  when: harden_testing_check

- name: Import testing-privesc
  ansible.builtin.import_tasks: testing-privesc.yml
  when: harden_testing_privesc

- name: Import testing-speculative
  ansible.builtin.import_tasks: testing-speculative.yml
  when: harden_testing_speculative
