---

- name: Debian | ensure unattended-upgrades is installed
  ansible.builtin.apt:
    name: unattended-upgrades
    state: present
  register: pkg_result
  until: pkg_result is success

## https://help.ubuntu.com/lts/serverguide/automatic-updates.html
- name: Debian | enable automatic security updates
  ansible.builtin.lineinfile:
    dest: "{{ aptconf_unattended | default('/etc/apt/apt.conf.d/10periodic') }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    mode: '0644'
    backup: "{{ harden_backup | default(false) }}"
  with_items:
    - { regexp: '^APT::Periodic::Update-Package-Lists', line: 'APT::Periodic::Update-Package-Lists "1";' }
    - { regexp: '^APT::Periodic::Download-Upgradeable-Packages',
        line: 'APT::Periodic::Download-Upgradeable-Packages "1";'
    }
    - { regexp: '^APT::Periodic::Unattended-Upgrade', line: 'APT::Periodic::Unattended-Upgrade "1";' }
    - { regexp: '^APT::Periodic::AutocleanInterval', line: 'APT::Periodic::AutocleanInterval "14";' }
    # more verbose
    # https://bugs.launchpad.net/ubuntu/+source/apt/+bug/2003851
    - { regexp: '^APT::Periodic::Verbose', line: 'APT::Periodic::Verbose "0";' }
    - { regexp: '^APT::Acquire::Retries .*', line: 'APT::Acquire::Retries "0";' }

- name: Debian | Ensure service.d directory exists
  ansible.builtin.file:
    path: /etc/systemd/system/apt-daily.service.d
    state: directory
    mode: '0755'
    owner: root

- name: Debian | Enforce run time limit
  ansible.builtin.copy:
    content: |
      [Service]
      RuntimeMaxSec=60
      RuntimeRandomizedExtraSec=15
    dest: /etc/systemd/system/apt-daily.service.d/runtimemax.conf
    mode: '0644'
    owner: root
