---

# - debug: var=ansible_mounts
# - debug: var=harden_mount_options

- name: backup fstab
  ansible.builtin.copy:
    src: /etc/fstab
    dest: "/etc/fstab.{{ ansible_date_time.date }}"
    mode: '0644'
    remote_src: true

## https://groups.google.com/forum/#!msg/ansible-project/7MhOICPWkaI/rADYaeaRDlsJ
- include_tasks: unix-fstab-mount.yml
  with_items: "{{ harden_mount_options }}"
  loop_control:
    loop_var: outer_item

- name: check fstab changes
  ansible.builtin.command: "diff /etc/fstab.{{ ansible_date_time.date }} /etc/fstab"
  changed_when: false
  ignore_errors: true
  register: diff
- name: Debug | fstab changes
  ansible.builtin.debug: var=diff.stdout_lines
