---

- name: USB | Ensure udev & others are present
  ansible.builtin.package: name={{ item }} state=present
  with_items:
    - udev
    - zenity
  register: pkg_result
  until: pkg_result is success

## FIXME! Currently not working
## https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1414409
##      systemd-udevd[257]: specified group 'input' unknown
## https://patchwork.ozlabs.org/patch/198234/
## https://bugs.freedesktop.org/show_bug.cgi?id=88491
- name: Patch udev init for missing group
  ansible.builtin.replace:
    dest: /etc/init.d/udev
    regexp: ' /sbin/udevd$'
    replace: ' /sbin/udevd --resolve-names=never'
    mode: '0644'
    backup: "{{ harden_backup | default(false) }}"
  when: ansible_os_family == 'Alpine'

- name: USB | add restriction rules
  ansible.builtin.template:
    src: 000_usbfilter.rules.j2
    dest: /etc/udev/rules.d/000_usbfilter.rules
    mode: '0644'
    backup: "{{ harden_backup | default(false) }}"
  notify:
    - reload udev
