FROM alpine:3.7
RUN apk update

# Install Ansible
RUN apk add git python python-dev py-pip alpine-sdk libffi-dev openssl-dev
RUN mkdir /etc/ansible

# Install Ansible inventory file
RUN (echo "[local]"; echo "localhost ansible_connection=local") > /etc/ansible/hosts
