# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
## for xenial, need to manually install python as python v2 is not in default image.
    #config.vm.box = "ubuntu/xenial64"
    config.vm.box = "boxcutter/ubuntu1604"
    #config.vm.box = "ubuntu/trusty64"
    #config.vm.box = "centos/7"
    #config.vm.box = "generic/alpine36"

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.become = true
       ansible.extra_vars = { ansible_ssh_user: 'vagrant', inspec_dir: '/vagrant' }
       ansible.groups = {
          "myrole" => ["harden" ],
       }
    end

    config.vm.define "harden" do |harden|
        harden.vm.hostname = "harden"
        harden.vm.provider "virtualbox" do |v|
          v.memory = 512
        end
    end

    config.vm.synced_folder "../integration/default/inspec", "/vagrant/inspec", disabled: false
end

