# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    config.vm.box = "ubuntu/jammy64"
    #config.vm.box = "generic/centos9s"

    # use hostname based on host
    config.vm.hostname = "#{`hostname`[0..-2]}".sub(/\..*$/,'')+"-harden-vagrant"

    config.vm.provision :ansible do |ansible|
       ansible.playbook = "site.yml"
       #ansible.verbose = "vvvv"
       #ansible.host_key_checking = false
       #ansible.limit = 'all'
       ansible.become = true
       #ansible.extra_vars = { ansible_ssh_user: 'vagrant', inspec_dir: '/vagrant', ansible_python_interpreter: '/usr/bin/python36' }
       ansible.extra_vars = { ansible_ssh_user: 'vagrant', inspec_dir: '/vagrant' }
       ansible.groups = {
          "myrole" => ["harden" ],
       }
    end

    config.vm.define "harden" do |harden|
        harden.vm.provider "virtualbox" do |v|
          v.memory = 512
        end
    end

    config.vm.synced_folder "../integration/default/inspec", "/vagrant/inspec", disabled: false
end
